name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  integration-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-e2e-pg16-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-e2e-pg16-
            ${{ runner.os }}-cargo-e2e-

      - name: Cache cargo-pgrx installation
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-pgrx
          key: ${{ runner.os }}-cargo-pgrx-0.14.3
          restore-keys: |
            ${{ runner.os }}-cargo-pgrx-

      - name: Cache PostgreSQL installations
        uses: actions/cache@v3
        with:
          path: ~/.pgrx
          key: ${{ runner.os }}-pgrx-pg16-0.14.3
          restore-keys: |
            ${{ runner.os }}-pgrx-pg16-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential protobuf-compiler libreadline-dev zlib1g-dev libssl-dev libicu-dev

      - name: Install and initialize pgrx
        run: |
          if [ ! -f ~/.cargo/bin/cargo-pgrx ]; then
            cargo install cargo-pgrx --version=0.14.3 --locked
            cargo pgrx init --pg16=download
          fi

      - name: Build extension for PostgreSQL 16
        run: |
          cargo pgrx package --no-default-features --features pg16

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install Python dependencies
        working-directory: integration_tests
        run: uv sync

      - name: Run integration tests
        working-directory: integration_tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
        env:
          PG_VERSION: 16

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-pg16
          path: |
            integration_tests/testdata/
            integration_tests/docker/logs/
          retention-days: 7
